meta:
  blobstore_bucket: (( param "specify blobstore bucket" ))
  bosh_domain_name: bosh
  env:
    name: bosh

name: (( param "specify deployment name" ))
director_uuid: (( param "specify bosh director" ))

releases:
- {name: bosh, version: latest}
- {name: bosh-aws-cpi, version: latest}
- {name: uaa, version: latest}
- {name: cron, version: latest}
- {name: ntp, version: latest}
- {name: secureproxy, version: latest}

update:
  canaries: 1
  canary_watch_time: 3000-180000
  update_watch_time: 3000-180000
  max_in_flight: 4

stemcells:
- alias: default
  name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
  version: latest

instance_groups:
- name: uaa
  stemcell: default
  vm_type: bosh
  persistent_disk_type: bosh
  instances: 1
  azs: [z1]
  jobs:
  - name: uaa
    release: uaa
    properties:
      uaadb:
        db_scheme: postgresql
        address: (( grab terraform_outputs.bosh_rds_host_curr ))
        port: 5432
        databases:
        - tag: uaa
          name: bosh_uaadb
        roles:
        - tag: admin
          name: (( grab terraform_outputs.bosh_rds_username ))
          password: (( grab terraform_outputs.bosh_rds_password ))

      uaa:
        url: https://localhost:8443
        sslCertificate: (( grab secrets.bosh_uaa_web_cert ))
        sslPrivateKey: (( grab secrets.bosh_uaa_web_key ))
        jwt:
          signing_key: (( grab secrets.bosh_uaa_web_key ))
          verification_key: (( grab secrets.bosh_uaa_web_public_key ))
        admin:
          client_secret: (( grab secrets.bosh_uaa_admin_client_secret ))
        login:
          client_secret: (( grab secrets.bosh_uaa_login_client_secret ))
        clients:
          hm:
            override: true
            authorized-grant-types: client_credentials
            scope: ""
            authorities: bosh.admin
            secret: (( grab secrets.bosh_uaa_hm_client_secret ))
          ci:
            authorized-grant-types: client_credentials
            scope: ""
            authorities: bosh.admin
            secret: (( grab secrets.bosh_uaa_ci_client_secret ))
          bosh_cli:
            override: true
            authorized-grant-types: password,refresh_token
            # scopes the client may receive
            scope: openid,bosh.admin,bosh.read,bosh.*.admin,bosh.*.read
            authorities: uaa.none
            access-token-validity: 1200 # 20 min
            refresh-token-validity: 86400 # re-login required once a day
            secret: ""
          bosh_exporter:
            override: true
            authorized-grant-types: client_credentials
            authorities: bosh.read
            scope: ""
            secret: (( grab secrets.bosh_uaa_bosh_exporter_client_secret ))
        scim:
          users:
          - name: admin
            password: (( grab secrets.bosh_admin_password ))
            groups:
            - scim.write
            - scim.read
            - bosh.admin
        zones:
          internal:
            hostnames:
            - (( grab terraform_outputs.bosh_static_ip ))

      login:
        url: https://localhost:8443
        protocol: https
        brand: oss
        brand_title: cloud.gov
        self_service_links_enabled: false
        signups_enabled: false
        invitations_enabled: false

  - name: secureproxy
    release: secureproxy
    properties:
      secureproxy:
        listen_port: 8081
        proxy_port: 8080

- name: bosh
  stemcell: default
  vm_type: bosh
  persistent_disk_type: bosh
  instances: 1
  azs: [z1]
  jobs:
  - name: nats
    release: bosh
    properties:
      nats:
        address: (( grab terraform_outputs.bosh_static_ip ))
        user: nats
        #allow_legacy_agents: false # this should be uncommented once all deployments are updated to use mtls
        password: (( grab secrets.bosh_nats_password ))
        tls:
          ca: (( grab secrets.ca_cert ))
          client_ca:
            certificate: (( grab secrets.ca_cert ))
            private_key: (( grab secrets.ca_key ))
          server:
            certificate: (( grab secrets.bosh_nats_server_cert ))
            private_key: (( grab secrets.bosh_nats_server_key ))
          director:
            certificate: (( grab secrets.bosh_nats_director_cert ))
            private_key: (( grab secrets.bosh_nats_director_key ))
          health_monitor:
            certificate: (( grab secrets.bosh_nats_hm_cert ))
            private_key: (( grab secrets.bosh_nats_hm_key ))

  - name: blobstore
    release: bosh
    properties:
      blobstore:
        provider: s3
        server_side_encryption: AES256
        credentials_source: env_or_profile
        bucket_name: (( grab meta.blobstore_bucket ))
        s3_region: (( grab terraform_outputs.vpc_region ))
        agent:
          user: agent
          password: (( grab secrets.bosh_agent_password ))
        director:
          user: director
          password: (( grab secrets.bosh_director_password ))

  - name: director
    release: bosh
    properties:
      director:
        name: bosh
        address: (( grab terraform_outputs.bosh_static_ip ))
        db:
          user: (( grab terraform_outputs.bosh_rds_username ))
          password: (( grab terraform_outputs.bosh_rds_password ))
          host: (( grab terraform_outputs.bosh_rds_host_curr ))
          database: bosh
          port: 5432
        ssl:
          cert: (( grab secrets.bosh_director_cert ))
          key: (( grab secrets.bosh_director_key ))
        cpi_job: aws_cpi
        flush_arp: true
        # TODO: Revert after https://github.com/cloudfoundry/bosh/issues/1486 is resolved
        enable_post_deploy: true
        workers: 5
        user_management:
          provider: uaa
          uaa:
            url: (( concat "https://0.uaa." meta.env.name "-bosh." meta.env.name "bosh.toolingbosh:8443" ))
            public_key: (( grab secrets.bosh_uaa_web_public_key ))
      nats: (( grab instance_groups.bosh.jobs.nats.properties.nats ))
      blobstore: (( grab instance_groups.bosh.jobs.blobstore.properties.blobstore ))
      dns: (( grab instance_groups.bosh.jobs.powerdns.properties.dns ))
      ntp:
      - (( grab terraform_outputs.bosh_static_ip ))

  - name: health_monitor
    release: bosh
    properties:
      hm:
        director_account:
          user: admin
          password: (( grab secrets.bosh_admin_password ))
          ca_cert: (( grab secrets.ca_cert ))
          client_id: hm
          client_secret: (( grab secrets.bosh_uaa_hm_client_secret ))
        resurrector_enabled: true
        resurrector:
          minimum_down_jobs: 3
      nats: (( grab instance_groups.bosh.jobs.nats.properties.nats ))
      director:
        address: (( grab terraform_outputs.bosh_static_ip ))

  - name: registry
    release: bosh
    properties:
      registry:
        address: (( grab terraform_outputs.bosh_static_ip ))
        host: (( grab terraform_outputs.bosh_static_ip ))
        db: (( grab instance_groups.bosh.jobs.director.properties.director.db ))
        http:
          user: registry
          password: (( grab secrets.bosh_registry_password ))
          port: 25777
        username: registry
        password: (( grab secrets.bosh_registry_password ))
        port: 25777
        cloud:
          plugin: aws
          credentials_source: env_or_profile
          region: (( grab terraform_outputs.vpc_region ))

  - name: powerdns
    release: bosh
    properties:
      dns:
        address: (( grab terraform_outputs.bosh_static_ip ))
        recursor: (( grab terraform_outputs.vpc_cidr_dns ))
        db: (( grab instance_groups.bosh.jobs.director.properties.director.db ))
        domain_name: (( grab meta.bosh_domain_name ))

  - name: aws_cpi
    release: bosh-aws-cpi
    properties:
      aws:
        credentials_source: env_or_profile
        default_key_name: (( grab secrets.ca_public_key_name ))
        default_security_groups:
        - (( grab terraform_outputs.bosh_security_group ))
        default_iam_instance_profile: (( grab terraform_outputs.default_profile ))
        region: (( grab terraform_outputs.vpc_region ))
      registry:
        username: registry
        password: (( grab secrets.bosh_registry_password ))
        host: (( grab terraform_outputs.bosh_static_ip ))
      nats: (( grab instance_groups.bosh.jobs.nats.properties.nats ))
      blobstore: (( grab instance_groups.bosh.jobs.blobstore.properties.blobstore ))
      ntp: (( grab instance_groups.bosh.jobs.director.properties.ntp ))

  - name: ntpd
    release: ntp
    properties:
      ntp_conf: |
        server time-a.nist.gov
        server time-b.nist.gov
        server time-c.nist.gov
        server time-d.nist.gov
        server time-b-wwv.nist.gov
        server time-c-wwv.nist.gov
        server time-d-wwv.nist.gov

  - name: cron
    release: cron
    properties:
      cron:
        variables:
          TOOLING_BOSH: (( grab terraform_outputs.tooling_bosh_static_ip ))
          AWS_DEFAULT_REGION: (( grab terraform_outputs.vpc_region ))
          PGHOST: (( grab terraform_outputs.bosh_rds_host_curr ))
          PGUSERNAME: (( grab terraform_outputs.bosh_rds_username ))
          PGPASSWORD: (( grab terraform_outputs.bosh_rds_password ))
          PGDBNAME: bosh
          VPC_NAME: (( grab terraform_outputs.stack_description ))
          BOSH_DIRECTOR: (( grab terraform_outputs.bosh_static_ip ))
          INSTANCE_WHITELIST: (( concat terraform_outputs.nat_private_ip_az1 " " terraform_outputs.nat_private_ip_az2 " " terraform_outputs.master_bosh_static_ip " " terraform_outputs.bosh_static_ip ))
        entries:
        - script:
            name: unknown-vms.sh
            contents: (( file "bosh-config/cronjobs/unknown-vms.sh" ))
          minute: '*'
          hour: '*'
          day: '*'
          month: '*'
          wday: '*'
          user: root
