releases:
- {name: fisma, version: (( grab $release_fisma ))}
- {name: tripwire, version: (( grab $release_tripwire ))}
- {name: clamav, version: (( grab $release_clamav ))}
- {name: snort, version: (( grab $release_snort ))}
- {name: awslogs, version: (( grab $release_awslogs ))}
- {name: nessus-agent, version: (( grab $release_nessus_agent ))}
- {name: node-exporter, version: (( grab $release_node_exporter ))}
- {name: syslog, version: (( grab $release_syslog ))}

addons:
- name: hardening
  jobs:
  - {name: harden, release: fisma}
  - {name: tripwire, release: tripwire}
  - {name: clamav, release: clamav}
  - {name: snort, release: snort}
  - {name: awslogs, release: awslogs}
  - {name: nessus-agent, release: nessus-agent}
  - {name: node_exporter, release: node-exporter}
  - {name: syslog_forwarder, release: syslog}
  properties:
    tripwire:
      localpass: (( grab $TRIPWIRE_LOCALPASS ))
      sitepass: (( grab $TRIPWIRE_SITEPASS ))
    awslogs:
      region: (( grab $AWS_REGION ))
    nessus-agent:
      key: (( grab $NESSUS_AGENT_KEY ))
      server: (( grab $NESSUS_AGENT_SERVER ))
      port: (( grab $NESSUS_AGENT_PORT ))
      group: (( grab $NESSUS_AGENT_GROUP ))
    syslog:
      address: (( grab terraform_outputs.platform_syslog_elb_dns_name ))
      port: 5514
