---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: 18fgsa/concourse-task

inputs:
- {name: bosh-config}
- {name: ca-cert-store}
- {name: terraform-yaml}

run:
  path: bosh-config/ci/update-cloud-config.sh
