azs:
- name: z1
  cloud_properties:
    availability_zone: ((terraform_outputs.az1))
- name: z2
  cloud_properties:
    availability_zone: ((terraform_outputs.az2))

vm_types:
- name: compilation
  cloud_properties:
    instance_type: c3.xlarge
    iam_instance_profile: ((terraform_outputs.bosh_compilation_profile))
    ephemeral_disk:
      size: 30000
- name: errand_small
  cloud_properties:
    instance_type: t2.small
- name: errand_large
  cloud_properties:
    instance_type: m4.large

vm_extensions:
- name: errand-profile
  cloud_properties:
    iam_instance_profile: ((terraform_outputs.bosh_compilation_profile))

networks: []
disk_types: []

compilation:
  workers: 5
  reuse_compilation_vms: true
  vm_type: compilation
  az: z1
