networks:
- name: default
  type: dynamic
  subnets:
  - az: z1
    range: (( grab terraform_outputs.private_subnet_cidr_az1 ))
    gateway: (( grab terraform_outputs.private_subnet_gateway_az1 ))
    reserved:
    - (( grab terraform_outputs.private_subnet_reserved_az1 ))
    - (( grab terraform_outputs.bosh_static_ip ))
    dns:
    - (( grab terraform_outputs.private_subnet_dns_az1 ))
    cloud_properties:
      subnet: (( grab terraform_outputs.private_subnet_az1 ))
      security_groups:
      - (( grab terraform_outputs.bosh_security_group ))
  - az: z2
    range: (( grab terraform_outputs.private_subnet_cidr_az2 ))
    gateway: (( grab terraform_outputs.private_subnet_gateway_az2 ))
    reserved:
    - (( grab terraform_outputs.private_subnet_reserved_az2 ))
    - (( grab terraform_outputs.bosh_static_ip ))
    dns:
    - (( grab terraform_outputs.private_subnet_dns_az2 ))
    cloud_properties:
      subnet: (( grab terraform_outputs.private_subnet_az2 ))
      security_groups:
      - (( grab terraform_outputs.bosh_security_group ))
- name: concourse
  type: manual
  subnets:
  - range: (( grab terraform_outputs.concourse_subnet_cidr ))
    gateway: (( grab terraform_outputs.concourse_subnet_gateway ))
    reserved:
    - (( grab terraform_outputs.concourse_subnet_reserved ))
    az: z2
    dns:
    - (( grab terraform_outputs.vpc_cidr_dns ))
    cloud_properties:
      subnet: (( grab terraform_outputs.concourse_subnet ))
      security_groups:
      - (( grab terraform_outputs.bosh_security_group ))
      - (( grab terraform_outputs.concourse_security_group ))

vm_types:
- name: admin-ui
  cloud_properties:
    instance_type: t2.medium
    ephemeral_disk:
      type: gp2
      size: 10240
      encrypted: true
- name: shibboleth
  cloud_properties:
    instance_type: m3.medium
    ephemeral_disk:
      type: gp2
      size: 10240
      encrypted: true
- name: concourse-web
  cloud_properties:
    instance_type: t2.medium
    ephemeral_disk:
      type: gp2
      size: 45000
      encrypted: true
- name: concourse-worker
  cloud_properties:
    instance_type: m3.xlarge
    ephemeral_disk:
      type: gp2
      size: 300000
      encrypted: true

disk_types:
- name: admin-ui
  disk_size: 5120
  cloud_properties:
    type: gp2
    encrypted: true
- name: shibboleth
  disk_size: 4096
  cloud_properties:
    type: gp2
    encrypted: true

vm_extensions:
- name: concourse-lb
  cloud_properties:
    elbs:
    - (( grab terraform_outputs.concourse_elb_name ))
- name: shibboleth-lb
  cloud_properties:
    elbs:
    - (( grab terraform_outputs.shibboleth_elb_name ))

compilation:
  network: default
