vm_types:
- name: logsearch_es_master
  cloud_properties:
    instance_type: t2.large
- name: logsearch_es_data
  cloud_properties:
    instance_type: t2.large
- name: logsearch_queue
  cloud_properties:
    instance_type: t2.large
- name: logsearch_ingestor
  cloud_properties:
    instance_type: t2.large
- name: logsearch_parser
  cloud_properties:
    instance_type: t2.large
- name: logsearch_kibana
  cloud_properties:
    instance_type: t2.large
- name: logsearch_maintenance
  cloud_properties:
    instance_type: t2.large
- name: logsearch_cluster_monitor
  cloud_properties:
    instance_type: t2.large
- name: kubernetes_consul
  cloud_properties:
    instance_type: t2.large
- name: kubernetes_etcd
  cloud_properties:
    instance_type: t2.large

disk_types:
- name: logsearch_es_data
  disk_size: 150000
