vm_types:
- name: bosh
  cloud_properties:
    instance_type: m3.large

networks:
- name: bosh
  type: manual
  subnets:
  - range: (( grab terraform_outputs.private_subnet_cidr_az1 ))
    gateway: (( grab terraform_outputs.private_subnet_gateway_az1 ))
    static:
    - (( grab terraform_outputs.tooling_bosh_static_ip ))
    reserved:
    - (( grab terraform_outputs.private_subnet_reserved_az1 ))
    dns: (( grab terraform_outputs.private_subnet_dns_az1 ))
    cloud_properties:
      subnet: (( grab terraform_outputs.private_subnet_az1 ))
      security_groups:
      - (( grab terraform_outputs.bosh_security_group ))

vm_extensions:
- name: bosh-profile
  cloud_properties:
    iam_instance_profile: (( grab terraform_outputs.bosh_profile ))

disk_types:
- name: bosh
  disk_size: 300000
  cloud_properties:
    type: gp2
    encrypted: true

compilation:
  network: bosh
